server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
        routes:
          - id: userUaeh
            uri: http://localhost:9090
            predicates:
              - Path=/api/userUaeh/**
          - id: post
            uri: http://localhost:8090
            predicates:
              - Path=/api/post/**